export type AppRoute =
  | 'launch.splash'
  | 'launch.onboarding'
  | 'home'
  | 'auth.signIn'
  | 'auth.signUp'
  | 'auth.phone'
  | 'auth.forgotPassword'
  | 'auth.verifyEmail'
  | 'auth.resetPassword'
  | 'profile.home'
  | 'profile.edit'
  | 'profile.statistics'
  | 'profile.invite'
  | 'profile.coupons'
  | 'membership.home'
  | 'membership.plans'
  | 'membership.checkout'
  | 'membership.orders'
  | 'settings.home'
  | 'settings.accountSecurity'
  | 'settings.devices'
  | 'settings.notifications'
  | 'settings.privacy'
  | 'settings.general'
  | 'settings.appearance'
  | 'settings.language'
  | 'settings.textSize'
  | 'settings.storage'
  | 'settings.permissions'
  | 'settings.helpFeedback'
  | 'support.newTicket'
  | 'support.ticket'
  | 'support.feedback'
  | 'settings.legal'
  | 'settings.privacyPolicy'
  | 'settings.termsOfService'
  | 'settings.subscriptionTerms'
  | 'settings.about'
  | 'settings.deleteAccount'
  | 'notifications.center'
  | 'states.gallery';

export type RouteEntry = Readonly<{
  key: string;
  name: AppRoute;
}>;
