import 'dart:convert';
import 'dart:io';

import 'arguments.dart';
import 'command_runner.dart';

final class FeatureCommand {
  int run(List<String> values) {
    if (values.isEmpty || values.first != 'add') {
      throw const MobileUiUsageException('expected feature add <feature-id>');
    }
    final arguments = CommandArguments(values.skip(1).toList());
    final featureId = arguments.positional(index: 0, label: 'feature id');
    final project = Directory(arguments.option('project'));
    _validateFeatureId(featureId);

    final metadata = File(_join(project.path, '.mobileui', 'template.json'));
    if (!metadata.existsSync()) {
      throw const MobileUiUsageException(
        'project is missing .mobileui/template.json',
      );
    }
    final manifest =
        jsonDecode(metadata.readAsStringSync()) as Map<String, Object?>;
    final profiles = _profiles(manifest);
    for (final profile in profiles) {
      final featureRoot = Directory(
        _featurePath(project.path, profile, featureId),
      );
      if (featureRoot.existsSync() && featureRoot.listSync().isNotEmpty) {
        throw MobileUiUsageException(
          'feature already exists for $profile: $featureId',
        );
      }
      _writeBoundary(featureRoot, featureId);
    }
    _registerFeature(metadata, manifest, featureId);
    stdout.writeln('Added feature "$featureId" to ${project.path}');
    return 0;
  }

  void _registerFeature(
    File metadata,
    Map<String, Object?> manifest,
    String featureId,
  ) {
    final features =
        (manifest['features'] as List<Object?>? ?? const [])
            .whereType<String>()
            .toSet()
          ..add(featureId);
    manifest['features'] = features.toList()..sort();
    metadata.writeAsStringSync(
      '${const JsonEncoder.withIndent('  ').convert(manifest)}\n',
    );
  }

  void _writeBoundary(Directory root, String featureId) {
    root.createSync(recursive: true);
    for (final layer in const [
      'domain',
      'application',
      'data',
      'presentation',
    ]) {
      Directory(_join(root.path, layer)).createSync(recursive: true);
    }
    File(_join(root.path, 'README.md')).writeAsStringSync('''
# $featureId

Feature ownership boundary generated by MobileUI.

- `domain/`: immutable entities and repository contracts
- `application/`: controller, typed events, and explicit async state
- `data/`: persistence and remote adapters implementing domain contracts
- `presentation/`: pages and components that only emit typed events

Dependencies point `presentation -> application -> domain`; data adapters
depend on domain contracts. Product code must be implemented from its approved
specification rather than generated placeholder behavior.
''');
  }

  List<String> _profiles(Map<String, Object?> manifest) {
    final profiles = (manifest['profiles'] as List<Object?>?)
        ?.whereType<String>()
        .toList();
    if (profiles != null && profiles.isNotEmpty) return profiles;
    final legacy = manifest['profile'] as String?;
    if (legacy == null || legacy == 'all') {
      throw const MobileUiUsageException('project has no supported profiles');
    }
    return [legacy];
  }

  String _featurePath(String project, String profile, String featureId) {
    return switch (profile) {
      'flutter' => _join(project, 'flutter', 'lib', 'features', featureId),
      'react-native' => _join(
        project,
        'react-native',
        'src',
        'features',
        featureId,
      ),
      'arkts' => _join(
        project,
        'arkts',
        'entry',
        'src',
        'main',
        'ets',
        'features',
        featureId,
      ),
      'server' => _join(project, 'server', 'src', 'features', featureId),
      'biz-server' => _join(
        project,
        'biz-server',
        'src',
        'features',
        featureId,
      ),
      _ => throw MobileUiUsageException('unsupported profile "$profile"'),
    };
  }

  void _validateFeatureId(String value) {
    if (!RegExp(r'^[a-z][a-z0-9-]*$').hasMatch(value)) {
      throw const MobileUiUsageException(
        'feature id must use lowercase kebab-case',
      );
    }
  }
}

String _join(
  String first, [
  String? second,
  String? third,
  String? fourth,
  String? fifth,
  String? sixth,
  String? seventh,
  String? eighth,
]) {
  return [
    first,
    second,
    third,
    fourth,
    fifth,
    sixth,
    seventh,
    eighth,
  ].whereType<String>().join(Platform.pathSeparator);
}
